PREFIX:=/home/d/pc2drc/libdrc-vnc/libdrc-thefloppydriver/build
DEMOS:=y
CXX:=g++
CXXFLAGS:=-O2 -fPIC -I include -Wall -Wextra -Wno-unused-parameter -Wno-unused-variable -std=gnu++11  -I/usr/include/x86_64-linux-gnu -I/home/d/pc2drc/drc-x264/build/include  -D_GNU_SOURCE=1 -D_REENTRANT -I/usr/include/SDL
LDFLAGS:= -lswscale -L/home/d/pc2drc/drc-x264/build/lib -lx264 -lpthread
LDFLAGS_DEMOS:=-lpthread -lGLEW -lGLU -lGL -lSDL
