ctrl_interface=/var/run/wpa_supplicant_drc
update_config=1

network={
	ssid="WiiU34af2ca17f30"
	psk=095b814181f52b7927c77b4d2ea60e9d0558e629d868091288a4fca0c791107e
	proto=RSN
	key_mgmt=WPA-PSK
	pairwise=CCMP
	auth_alg=OPEN
}
